name: Today in Science CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js versions ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - run: npm run install-server
      - run: npm test
